// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH-EtATdQbdOe4OjKC_taU5sXOsV6pbTc',
    appId: '1:90875001267:web:838d72cc9d0ece144df3c6',
    messagingSenderId: '90875001267',
    projectId: 'bitelogik',
    authDomain: 'bitelogik.firebaseapp.com',
    storageBucket: 'bitelogik.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0F71PXoDLyslaUs9A3Dm8JyT70onPamk',
    appId: '1:90875001267:android:4e779a280edd8a274df3c6',
    messagingSenderId: '90875001267',
    projectId: 'bitelogik',
    storageBucket: 'bitelogik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgyebcWHI7aF8m-zrTEA0gEb6G8sX1hZY',
    appId: '1:90875001267:ios:0cfe2fc6d7649b684df3c6',
    messagingSenderId: '90875001267',
    projectId: 'bitelogik',
    storageBucket: 'bitelogik.firebasestorage.app',
    iosClientId: '90875001267-sfhq6dm3sskdaubmjhuj2buvcp9n60d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitelogik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgyebcWHI7aF8m-zrTEA0gEb6G8sX1hZY',
    appId: '1:90875001267:ios:0cfe2fc6d7649b684df3c6',
    messagingSenderId: '90875001267',
    projectId: 'bitelogik',
    storageBucket: 'bitelogik.firebasestorage.app',
    iosClientId: '90875001267-sfhq6dm3sskdaubmjhuj2buvcp9n60d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitelogik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH-EtATdQbdOe4OjKC_taU5sXOsV6pbTc',
    appId: '1:90875001267:web:c46aa2ecb39c1bbf4df3c6',
    messagingSenderId: '90875001267',
    projectId: 'bitelogik',
    authDomain: 'bitelogik.firebaseapp.com',
    storageBucket: 'bitelogik.firebasestorage.app',
  );
}
